config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  # For general sign up and user profile we have some unique urls
  get '/profile', to: 'users#profile'
  post '/users', to: 'users#create'

  # For session management we have unique urls
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy' # Added so we can use a simple link
  get '/signup', to: 'sessions#signup'

  resources :accounts, except: [:new, :show]
  resources :transactions
  resources :categories
  resources :category_groups
end

app/models/account.rb
# frozen_string_literal: true
class Account < ApplicationRecord
  belongs_to :user
  belongs_to :account_type
  has_many :transactions, dependent: :destroy

  validates :name, presence: true
  validates :account_type, presence: true
  validates :name, uniqueness: {scope: :user, message: 'Account names should be unique'}

  delegate :name, to: :account_type, prefix: true

  def active?
    deactive_at.nil? || dactive_at > Time.zone.now
  end
end

app/models/account_type.rb
# frozen_string_literal: true
class AccountType < ApplicationRecord
  has_many :accounts
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true
class AccountsController < ApplicationController
  before_action :set_account, only: %i(show edit update destroy)

  # GET /accounts
  def index
    @account = Account.new
    @accounts = policy_scope(Account)
  end

  # POST /accounts
  def create
    @account = Account.new(account_params.merge(user: current_user))

    if @account.save
      redirect_to transactions_url(account_id: @account.id), success: 'Account was successfully created.'
    else
      redirect_to transactions_url, alert: 'Error creating account.'
    end
  end

  # PATCH/PUT /accounts/1
  def update
    if @account.update(account_params)
      redirect_to @account, notice: 'Account was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /accounts/1
  def destroy
    @account.destroy
    redirect_to transactions_url, notice: 'Account was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def account_params
    params.require(:account).permit(:name, :note, :balance, :account_type_id)
  end
end

app/helpers/accounts_helper.rb
# frozen_string_literal: true
module AccountsHelper
  def account_class(account)
    'danger' unless account.active?
  end

  def accounts_list
    policy_scope(Account)
  end
end

app/views/accounts/list/_account.html.erb
<li class="sub-pill<%= active_transaction_link?(account.id) %>" id="account_nav_link_<%= account.id %>">
  <ul class="nav nav-pills nav-edit">
    <li class="account-link<%= active_transaction_link?(account.id) %>"><%= link_to account.name, transactions_url(account_id: account.id) %></li>
    <li class="pull-right">
      <%= link_to(account_url(id: account.id), method: :delete, class: 'account-delete', data: {accountid: account.id, confirm: 'Are you sure?'}) do %>
        <i class="fa fa-trash-o text-danger" ></i>
      <% end %>
    </li>
  </ul>
</li>

app/views/accounts/list/_add_account.html.erb
<li>
  <a href='#' class="pull-right text-success" data-toggle="modal" data-target="#add-account-modal">
    <i class="fa fa-plus text-success"></i> Add Account
  </a>
  <%= render partial: 'accounts/form/dialog_form', locals: {account: Account.new} %>
</li>

app/views/accounts/list/_list.html.erb
<ul class="nav nav-pills nav-stacked labels-info" id="account_list">
  <li class="<%= active_transaction_link? %>"><%= link_to 'All Accounts', transactions_url, id: 'all_accounts_link' %></li>
  <%= render partial: 'accounts/list/account', collection: accounts_list %>
  <%= render partial: 'accounts/list/add_account' %>
</ul>