config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  # For general sign up and user profile we have some unique urls
  get '/profile', to: 'users#profile'
  post '/users', to: 'users#create'

  # For session management we have unique urls
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy' # Added so we can use a simple link
  get '/signup', to: 'sessions#signup'

  resources :accounts, except: [:new, :show]
  resources :transactions
  resources :categories
  resources :category_groups
end

app/models/category_group.rb
# frozen_string_literal: true
class CategoryGroup < ApplicationRecord
  belongs_to :user
  has_many :categories, dependent: :destroy

  validates :name, presence: true
  validates :user, presence: true
  validates :name, uniqueness: {scope: :user, message: 'Category group names should be unique'}
end

app/controllers/category_groups_controller.rb
# frozen_string_literal: true
class CategoryGroupsController < ApplicationController
  before_action :set_category_group, only: %i(show edit update destroy)

  # GET /category_groups
  def index
    @category_groups = policy_scope(CategoryGroup)
  end

  # GET /category_groups/1
  def show; end

  # GET /category_groups/new
  def new
    @category_group = CategoryGroup.new
  end

  # GET /category_groups/1/edit
  def edit; end

  # POST /category_groups
  def create
    @category_group = CategoryGroup.new(category_group_params.merge(user: current_user))

    if @category_group.save
      redirect_to @category_group, notice: 'Category group was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /category_groups/1
  def update
    if @category_group.update(category_group_params)
      redirect_to @category_group, notice: 'Category group was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /category_groups/1
  def destroy
    @category_group.destroy
    redirect_to category_groups_url, notice: 'Category group was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category_group
    @category_group = CategoryGroup.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def category_group_params
    params.require(:category_group).permit(:name)
  end
end

app/helpers/category_groups_helper.rb
# frozen_string_literal: true
module CategoryGroupsHelper
end

app/views/category_groups/_form.html.erb
<%= bootstrap_form_for(category_group, layout: :horizontal, label_col: 'col-sm-2', control_col: 'col-sm-10') do |f| %>
  <%= f.alert_message "Please fix the errors below." %>
  <%= f.text_field :name %>
  <%= f.form_group do %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/category_groups/edit.html.erb
<%= render 'form', category_group: @category_group %>

app/views/category_groups/index.html.erb
<div class="table-responsive">
  <table class="table table-hover table-condensed table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @category_groups.each do |category_group| %>
        <tr>
          <td><%= category_group.name %></td>
          <td>
            <div class="btn-group" role="group">
              <%= link_to('Show', category_group, class: 'btn btn-sm btn-info') if policy(category_group).show? %>
              <%= link_to('Edit', edit_category_group_path(category_group), class: 'btn btn-sm btn-warning') if policy(category_group).update? %>
              <%= link_to('Destroy', category_group, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger') if policy(category_group).destroy? %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

<div class="row">
  <div class="col-md-3 col-md-offset-9">
    <%= link_to 'New Category Group', new_category_group_path, class: 'pull-right btn btn-primary' %>
  </div>
</div>

app/views/category_groups/new.html.erb
<h1>New Category Group</h1>
<%= render 'form', category_group: @category_group %>

app/views/category_groups/show.html.erb
<h1><%= @category_group.name %></h1>

<div class="row">
  <div class="col-md-3 col-md-offset-9">
    <%= link_to 'Edit', edit_category_group_path(@category_group), class: 'pull-right btn btn-warning' %>
  </div>
</div>