config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  # For general sign up and user profile we have some unique urls
  get '/profile', to: 'users#profile'
  post '/users', to: 'users#create'

  # For session management we have unique urls
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy' # Added so we can use a simple link
  get '/signup', to: 'sessions#signup'

  resources :accounts, except: [:new, :show]
  resources :transactions
  resources :categories
  resources :category_groups
end

app/models/category.rb
# frozen_string_literal: true
class Category < ApplicationRecord
  belongs_to :category_group

  validates :name, presence: true
  validates :category_group, presence: true
  validates :name, uniqueness: {scope: :category_group, message: 'Category names should be unique per group'}

  delegate :user, to: :category_group
  delegate :name, to: :category_group, prefix: true
end

app/controllers/categories_controller.rb
# frozen_string_literal: true
class CategoriesController < ApplicationController
  before_action :ensure_category_groups
  before_action :set_category, only: %i(show edit update destroy)

  # GET /categories
  def index
    @categories = policy_scope(Category)
  end

  # GET /categories/1
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private

  def ensure_category_groups
    return true if current_user.category_groups.count.positive?
    redirect_to category_groups_url, notice: 'You need to create a category group before accessing categories'
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def category_params
    params.require(:category).permit(:name, :category_group_id)
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= bootstrap_form_for(category, layout: :horizontal, label_col: 'col-sm-2', control_col: 'col-sm-10') do |f| %>
  <%= f.alert_message "Please fix the errors below." %>
  <%= f.collection_select :category_group_id, policy_scope(CategoryGroup), :id, :name %>
  <%= f.text_field :name %>
  <%= f.form_group do %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/categories/edit.html.erb
<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<div class="table-responsive">
  <table class="table table-hover table-condensed table-bordered table-striped">
    <thead>
      <tr>
        <th>Category group</th>
        <th>Name</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.category_group_name %></td>
          <td><%= category.name %></td>
          <td>
            <div class="btn-group" role="group">
              <%= link_to('Show', category, class: 'btn btn-sm btn-info', role: 'button') if policy(category).show? %>
              <%= link_to('Edit', edit_category_path(category), class: 'btn btn-sm btn-warning') if policy(category).update? %>
              <%= link_to('Delete', category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger', role: 'button') if policy(category).destroy? %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="row">
  <div class="col-md-3 col-md-offset-9">
    <%= link_to 'New Category', new_category_path, class: 'pull-right btn btn-primary' %>
  </div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<p>
  <strong>Category group:</strong>
  <%= @category.category_group_name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<div class="row">
  <div class="col-md-3 col-md-offset-9">
    <%= link_to 'Edit', edit_category_path(@category), class: 'pull-right btn btn-warning' %>
  </div>
</div>