config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  # For general sign up and user profile we have some unique urls
  get '/profile', to: 'users#profile'
  post '/users', to: 'users#create'

  # For session management we have unique urls
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy' # Added so we can use a simple link
  get '/signup', to: 'sessions#signup'

  resources :accounts, except: [:new, :show]
  resources :transactions
  resources :categories
  resources :category_groups
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissable fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Budget Me by <a href="mail:steven.bengtson@me.com">Steven Bengtson</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css' %>
<%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
<%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css' %>
<%= stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/bootstrap-combobox/1.1.7/css/bootstrap-combobox.min.css' %>
<%= stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.45/css/bootstrap-datetimepicker.min.css' %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<%= javascript_include_tag 'jquery', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'jquery_ujs', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js' %>
<%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/bootstrap-combobox/1.1.7/js/bootstrap-combobox.min.js' %>
<%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment-with-locales.min.js' %>
<%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.45/js/bootstrap-datetimepicker.min.js' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="col-sm-2">
  <ul class="nav nav-pills nav-stacked">
    <% if logged_in? %>
    <%= render partial: 'accounts/list/list' %>
    <li class="<%= active_link?('category_groups') %>"><%= link_to "Category Groups", category_groups_url %></li>
    <li class="<%= active_link?('categories') %>"><%= link_to "Categories", categories_url %></li>
    <li><%= link_to 'Log out', logout_url, method: :delete, class: 'nav-link' %></li>
    <% else %>
    <li><%= link_to "Log in", login_url, class: 'nav-link' %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>

    <div class="container-fluid">
      <div class="row">
        <% if content_for?(:content) %>
          <%= yield(:content) %>
        <% else %>
        <%= render partial: 'layouts/sidebar' %>
        <div class="col-md-10">
          <%= yield %>
        </div>
        <% end %>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/sessions.html.erb
<% content_for :content do %>
  <div class="col-md-12">
    <%= yield %>
  </div>
<% end %>
<%= render template: "layouts/application" %>